### ISSUE TITLE
Version string always be uppercase

### ISSUE THREAD

**Issue by gluons** [shinate/gulp-version-number#1]
``` javascript
gulp.src('src/*')
.pipe(version({
    value: 'v1.0.0',
    replaces: [
        /#version#/g
    ]
}))
.pipe(gulp.dest('dist'));
```

`v1.0.0` will be with `V1.0.0` in dest file. All alphabet in version string will be change to uppercase.
Please retain original version string.

[index.js#L86](https://github.com/shinate/gulp-version-number/blob/cf761968f4341182518ae61bb5276734e1319b60/index.js#L86)

**Comment by shinate** [comment]
0.1.5 published

**Comment by shinate** [comment]
fixed
