### ISSUE TITLE
Append breaking on AngularJS directive

### ISSUE THREAD

**Issue by sbnedkov** [shinate/gulp-version-number#3]
Hello and thanks for a great utility - I wouldn't have been sure my approach to versioning is correct without it.

I'm running into an exception when it tries to replace an AngularJS directive though:

>  &lt;img-crop/&gt;

[caused by this line:](https://github.com/shinate/gulp-version-number/blob/master/index.js#L247)
> var sts = content.match(/&lt;img[^&gt;]*&gt;/g);

Maybe this matching and the other similar lines can benefit from a space after the tag name, correct me if I'm wrong.

**Comment by shinate** [comment]
Thanks for your advice, it has been amended.

**Comment by sbnedkov** [comment]
Cool, thanks. I'll close this issue.
